lints.workspace = true

[package]
name = "gix-bundle"
version = "0.1.0"
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "Read and write git bundle files"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.82"
include = ["src/**/*", "examples/**/*", "LICENSE-*"]

[lib]
doctest = false

[features]
default = ["sha1"]
## Enable support for SHA-1 object ids.
sha1 = ["gix-hash/sha1"]
## Enable support for SHA-256 object ids.
sha256 = ["gix-hash/sha256"]

[dependencies]
gix-hash = { version = "^0.25.0", path = "../gix-hash" }
gix-validate = { version = "^0.11.1", path = "../gix-validate" }

bstr = { version = "1.12.0", default-features = false, features = ["std"] }
thiserror = "2.0.18"

[dev-dependencies]
gix-testtools = { path = "../tests/tools" }
