lints.workspace = true

[package]
name = "gix-fetchhead"
version = "0.0.0"
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project to read and write .git/FETCH_HEAD"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2024"
rust-version = "1.85"
include = ["/src/**/*", "/LICENSE-*"]

[lib]
doctest = false

[features]
default = ["sha1"]
## Support SHA-1 object ids in FETCH_HEAD entries.
sha1 = ["gix-hash/sha1"]
## Support SHA-256 object ids in FETCH_HEAD entries.
sha256 = ["gix-hash/sha256"]

[dependencies]
bstr = { version = "1.12.0", default-features = false, features = ["std"] }
gix-hash = { version = "^0.25.0", path = "../gix-hash" }
