lints.workspace = true

[package]
name = "gix-traverse"
version = "0.57.0"
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2024"
include = ["/src/**/*", "/examples/**/*", "/LICENSE-*"]
rust-version = "1.85"

[lib]
doctest = false

[features]
## Enable support for the SHA-1 hash by enabling the respective feature in the `gix-hash` crate.
sha1 = ["gix-hash/sha1"]
## Enable support for the SHA-256 hash by enabling the respective feature in the `gix-hash` crate.
sha256 = ["gix-hash/sha256"]

[dependencies]
gix-hash = { version = "^0.25.0", path = "../gix-hash" }
gix-object = { version = "^0.60.0", path = "../gix-object" }
gix-date = { version = "^0.15.3", path = "../gix-date" }
gix-hashtable = { version = "^0.15.0", path = "../gix-hashtable" }
gix-revwalk = { version = "^0.31.0", path = "../gix-revwalk" }
gix-commitgraph = { version = "^0.37.0", path = "../gix-commitgraph" }
smallvec = "1.15.1"
thiserror = "2.0.18"
bitflags = "2"

[dev-dependencies]
gix-hash = { path = "../gix-hash", features = ["sha1"] }
gix-testtools = { path = "../tests/tools", default-features = false }
gix-odb = { path = "../gix-odb", features = ["sha1"] }
gix-object = { path = "../gix-object" }
gix-commitgraph = { path = "../gix-commitgraph" }
gix-path = { path = "../gix-path" }
insta = "1.46.3"

[package.metadata.docs.rs]
features = ["sha1"]
