lints.workspace = true

[package]
name = "gix-pack"
version = "0.70.0"
repository = "https://github.com/GitoxideLabs/gitoxide"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
license = "MIT OR Apache-2.0"
description = "Implements git packs and related data structures"
edition = "2024"
include = ["/src/**/*", "/examples/**/*", "/LICENSE-*"]
rust-version = "1.85"

[lib]
doctest = false

[features]
default = ["generate", "streaming-input"]
## Enable support for the SHA-1 hash by enabling the respective feature in the `gix-hash` crate.
sha1 = ["gix-hash/sha1"]
## Enable support for the SHA-256 hash by enabling the respective feature in the `gix-hash` crate.
sha256 = ["gix-hash/sha256"]
## generate new packs from a set of objects.
generate = ["dep:gix-traverse", "dep:gix-diff", "dep:parking_lot", "dep:gix-hashtable"]
## Receive a pack as datastream and resolve it
streaming-input = ["dep:parking_lot", "dep:gix-tempfile"]
## Provide a fixed-size allocation-free LRU cache for packs. It's useful if caching is desired while keeping the memory footprint
## for the LRU-cache itself low.
pack-cache-lru-static = ["dep:uluru"]
## Provide a hash-map based LRU cache whose eviction is based a memory cap calculated from object data.
pack-cache-lru-dynamic = ["dep:clru"]
## If set, select algorithms may additionally use a full-object cache which is queried before the pack itself.
object-cache-dynamic = ["dep:clru", "dep:gix-hashtable"]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "gix-object/serde"]
## Enable parallel algorithms.
parallel = ["gix-features/parallel"]
## Make it possible to compile to the `wasm32-unknown-unknown` target.
wasm = ["gix-diff?/wasm"]

[dependencies]
gix-features = { version = "^0.48.0", path = "../gix-features", features = ["crc32", "progress", "zlib"] }
gix-path = { version = "^0.12.0", path = "../gix-path" }
gix-hash = { version = "^0.25.0", path = "../gix-hash" }
gix-chunk = { version = "^0.7.1", path = "../gix-chunk" }
gix-error = { version = "^0.2.3", path = "../gix-error" }
gix-object = { version = "^0.60.0", path = "../gix-object" }
gix-hashtable = { version = "^0.15.0", path = "../gix-hashtable", optional = true }

# for streaming of packs (input, output)
gix-traverse = { version = "^0.57.0", path = "../gix-traverse", optional = true }
gix-diff = { version = "^0.63.0", path = "../gix-diff", default-features = false, optional = true }

memmap2 = "0.9.10"
smallvec = "1.15.1"
parking_lot = { version = "0.12.4", default-features = false, optional = true }
thiserror = "2.0.18"

# for caching
uluru = { version = "3.0.0", optional = true }
clru = { version = "0.6.1", optional = true }

serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"] }
## If enabled, `cargo doc` will see feature documentation from this manifest.
document-features = { version = "0.2.0", optional = true }


[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
gix-tempfile = { version = "^23.0.0", default-features = false, path = "../gix-tempfile", optional = true }

[dev-dependencies]
gix-pack = { path = ".", features = ["sha1", "sha256", "pack-cache-lru-dynamic", "pack-cache-lru-static", "object-cache-dynamic", "serde"] }
gix-testtools = { path = "../tests/tools", default-features = false }
gix-odb = { path = "../gix-odb", features = ["sha1", "sha256"] }
gix-object = { path = "../gix-object" }
gix-traverse = { path = "../gix-traverse" }
bstr = { version = "1.12.0", default-features = false, features = ["std"] }
maplit = "1.0.2"
memmap2 = "0.9.10"
proptest = "1"

[package.metadata.docs.rs]
all-features = true
features = ["sha1", "sha256", "document-features", "pack-cache-lru-dynamic", "object-cache-dynamic", "serde"]
