[package]
name = "gix-pack-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
anyhow = "1.0.100"
arbitrary = { version = "1", features = ["derive"] }
libfuzzer-sys = "0.4"
tempfile = "3"

[dependencies.gix-features]
path = "../../gix-features"
features = ["progress", "zlib"]

[dependencies.gix-hash]
path = "../../gix-hash"
features = ["sha1"]

[dependencies.gix-pack]
path = ".."
features = ["sha1"]

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[profile.release]
debug = 1

[[bin]]
name = "data_file"
path = "fuzz_targets/data_file.rs"
test = false
doc = false

[[bin]]
name = "index_file"
path = "fuzz_targets/index_file.rs"
test = false
doc = false

[[bin]]
name = "multi_index_file"
path = "fuzz_targets/multi_index_file.rs"
test = false
doc = false

[[bin]]
name = "pack_header"
path = "fuzz_targets/pack_header.rs"
test = false
doc = false

[[bin]]
name = "pack_entry"
path = "fuzz_targets/pack_entry.rs"
test = false
doc = false

[[bin]]
name = "delta_apply"
path = "fuzz_targets/delta_apply.rs"
test = false
doc = false
